site_name: matbii
site_url: https://dicelab-rhul.github.io/matbii/

nav:
  - Home: index.md
  - Getting started: 
    - Getting started: getting_started/index.md
    - Configuration: getting_started/configuration.md
    - Experiments: getting_started/experiments.md
    - Devices:
      - Devices: getting_started/devices/index.md
      - Mouse & keyboard: getting_started/devices/mouse_keyboard.md
      - Eye tracking: getting_started/devices/eye_tracking.md
      - Window & UI: getting_started/devices/window_ui.md
      - Advanced: getting_started/devices/advanced.md


  - Reference: reference/  

theme:
  name: material
  features:
    - content.code.copy
    - navigation.footer
    - navigation.expand
    - navigation.tabs
    - navigation.indexes 
  
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            preload_modules: [pydantic, icua]
            docstring_style: google
  - gen-files:
      scripts:
      - scripts/docs/gen_ref_pages.py
  - literate-nav
  - autorefs
  - section-index
  - macros:
      module_name: scripts/docs/macros

extra:
  version:
    provider: mike

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.extra
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

