site_name: matbii
site_url: https://dicelab-rhul.github.io/matbii/

nav:
  - Home: index.md
  - Getting started: 
    - Getting started: getting_started/index.md
    - Key Concepts: getting_started/key-concepts.md
    - Configuration: getting_started/configuration.md
    - Experiments:
      - Experiments: getting_started/experiments/index.md
      - Logging: getting_started/experiments/logging.md
      - Post analysis: getting_started/experiments/post-analysis.md
    - Devices:
      - Devices: getting_started/devices/index.md
      - Mouse & keyboard: getting_started/devices/mouse_keyboard.md
      - Eye tracking: getting_started/devices/eye_tracking.md
      - Window & UI: getting_started/devices/window_ui.md
  - Advanced: 
    - Advanced: advanced/index.md
    - Custom Entry Points: advanced/custom_entry_points.md
    - Custom Tasks: advanced/custom_tasks.md
    - Custom Devices: advanced/custom_devices.md
  - Reference: reference/  

theme:
  name: material
  features:
    - content.code.copy
    - navigation.footer
    - navigation.expand
    - navigation.tabs
    - navigation.indexes 
  
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            preload_modules: [pydantic, icua]
            docstring_style: google
  - gen-files:
      scripts:
      - scripts/docs/gen_ref_pages.py
  - literate-nav
  - autorefs
  - section-index
  - macros:
      module_name: scripts/docs/macros

extra:
  version:
    provider: mike

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.extra
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg